"""Session SPI — protocol for managing Claude Code sessions."""
from __future__ import annotations

from typing import Protocol

from commands.events import IssueContext


class SessionProvider(Protocol):
    def start(self, context: IssueContext) -> None: ...
    def run(self) -> None: ...
    def is_active(self) -> bool: ...
    def stop(self) -> None: ...
